POST https://fathomless-scrubland-50635.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Nick Kerr",
  "number": "100000000"
}

###

GET https://fathomless-scrubland-50635.herokuapp.com/api/persons