POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Nick Kerr",
  "number": "1000000000"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Nick Kerr",
  "number": "1000000000"
}

###

GET https://fathomless-scrubland-50635.herokuapp.com/api/persons

###
//Post with localhost
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mike Coxlong",
  "number": "30303030"
}

###
GET http://localhost:3001/api/persons