//gets the entire list of persons

GET https://fathomless-scrubland-50635.herokuapp.com/api/persons
###

DELETE https://fathomless-scrubland-50635.herokuapp.com/api/persons/3

###

GET https://fathomless-scrubland-50635.herokuapp.com/api/persons

//works as expected, list now has no entry with id = 3